replicaCount: 2

image:
  repository: jcscottiii/jamescscott.io
  pullPolicy: IfNotPresent


podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: jamescscott.io
      paths: 
        - /
  tls:
   - secretName: jamescscott-io-prod-blog-cert
     hosts:
       - jamescscott.io
