name: Deploy to prod

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show personal > $GITHUB_WORKSPACE/.kubeconfig
    - name: Helm Lint
      run: |
        echo "OK"
        helm version
        helm lint charts/blog
        APP_VERSION=$(helm show chart charts/blog | grep "appVersion:" | sed "s/appVersion:\s*//g")
        echo "::set-env name=APP_VERSION::$APP_VERSION"
        echo "Found app version $APP_VERSION"
    - name: Docker push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jcscottiii/jamescscott.io
        tags: ${{ env.APP_VERSION }}
    - name: Helm Deploy
      run: |
        echo "Deploying app version $APP_VERSION"
        helm -n jamescscott-io --kubeconfig $GITHUB_WORKSPACE/.kubeconfig upgrade --install jamescscott-io-prod charts/blog -f charts/blog/prod-values.yaml
